---
title: "Class Work 15.1"
output: html_document
date: '2022-05-30'
---

```{r}
setwd("/Users/uzmasyed/Library/Mobile Documents/com~apple~CloudDocs/GW Data Science/Class Folder/Module 15 Stat and R/Statistics and R/01_Demo/Statistics-and-R")
```


```{r}
library(tidyverse)
library(jsonlite)
demo_table2 <- fromJSON(txt='demo.json')
head(mpg)
```
```{r}
str(mpg)
```


```{r}
demo_table <- read.csv(file='demo.csv',check.names=F,stringsAsFactors = F)
head(demo_table)
```

```{r}
mpg_summary <- subset(mpg,manufacturer=="toyota") %>% group_by(cyl) %>% summarize(Mean_Hwy=mean(hwy), .groups = 'keep') #create summary table

mpg_summary

```

```{r}
plt <- ggplot(mpg_summary,aes(x=cyl,y=Mean_Hwy)) #import dataset into ggplot2

plt
```
```{r}
plt <- ggplot(mpg,aes(x=class, fill=class)) #import dataset into ggplot2
plt + geom_bar()+ labs(x="Class Type", y="Count of Class Type",
               title="Count of Class Type") #plot a bar plot
```
```{r}
ggplot(mtcars,aes(x=wt)) + geom_density() #visualize distribution using density plot
```

```{r}
population_table <- read.csv('used_car_data.csv',check.names = F,stringsAsFactors = F) #import used car dataset
plt <- ggplot(population_table,aes(x=log10(Miles_Driven))) #import dataset into ggplot2
plt + geom_density() #visualize distribution using density plot
```
```{r}
```


```{r}
population_table <- read.csv('used_car_data.csv',check.names = F,stringsAsFactors = F) #import used car dataset
plt <- ggplot(population_table,aes(x=log10(Miles_Driven))) #import dataset into ggplot2
plt + geom_density() #visualize distribution using density plot


```
```{r}
sample_table <- population_table %>% sample_n(50) #randomly sample 50 data points
plt <- ggplot(sample_table,aes(x=log10(Miles_Driven))) #import dataset into ggplot2
plt + geom_density() #visualize distribution using density plot


```

```{r}
t.test(log10(sample_table$Miles_Driven),mu=mean(log10(population_table$Miles_Driven))) #compare sample versus population means
```

```{r}
sample_table <- population_table %>% sample_n(50) #generate 50 randomly sampled data points
sample_table2 <- population_table %>% sample_n(50) #generate another 50 randomly sampled data points
t.test(log10(sample_table$Miles_Driven),log10(sample_table2$Miles_Driven)) #compare means of two samples

```

```{r}
mpg_data <- read.csv('mpg_modified.csv') #import dataset
mpg_1999 <- mpg_data %>% filter(year==1999) #select only data points where the year is 1999
mpg_2008 <- mpg_data %>% filter(year==2008) #select only data points where the year is 2008
t.test(mpg_1999$hwy,mpg_2008$hwy,paired = T) #compare the mean difference between two samples
```

